package com.networknt.schema;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import com.networknt.schema.JsonSchema;
import com.networknt.schema.JsonSchemaFactory;

import com.networknt.schema.MyUtils.LatencyTimer;
import java.io.IOException;
import java.sql.SQLOutput;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.Set;

public class MyTest {

    public static void main(String[] args) throws IOException {
        String jsonInString = "{\n"
                + "  \"eventId\": \"e1781649-6572-4e94-8c45-9b76adfe567b\",\n"
                + "  \"eventTime\": 1518283236000,\n"
                + "  \"traceId\": \"a06dfe00-44b6-4cba-984c-6ab4551f05f3\",\n"
                + "  \"childrenEventNames\": [\n"
                + "    \"fkint/cp/ca_discover/ProductPageServed\"\n"
                + "  ],\n"
                + "  \"seqId\": \"001518283236000000000\",\n"
                + "  \"ingestedAt\": 1518283236743,\n"
                + "  \"parentId\": null,\n"
                + "  \"test\": \"NFR_TEST\",\n"
                + "  \"parentVersion\": null,\n"
                + "  \"schemaVersion\": \"2.5\",\n"
                + "  \"encodingType\": \"JSON\",\n"
                + "  \"data\": {\n"
                + "    \"debug\": {\n"
                + "      \"hostName\": \"fk-mobile-api-mapi-client-grp-18-457494\"\n"
                + "    },\n"
                + "    \"core\": {\n"
                + "      \"timestamp\": 1518283236742,\n"
                + "      \"requestId\": \"e1781649-6572-4e94-8c45-9b76adfe567b\",\n"
                + "      \"sourceClient\": \"AndroidApp\",\n"
                + "      \"URI\": \"/3/page/dynamic/product\"\n"
                + "    },\n"
                + "    \"visit\": {\n"
                + "      \"visitorId\": \"VI1816BC5E890745DC8C0531FBC956F878\",\n"
                + "      \"location\": {\n"
                + "        \"info\": {\n"
                + "          \"geolocation\": {},\n"
                + "          \"ipLocation\": {\n"
                + "            \"ip\": \"49.15.203.205\",\n"
                + "            \"country\": \"India\",\n"
                + "            \"state\": \"Kerala\",\n"
                + "            \"city\": \"UNKNOWN\"\n"
                + "          },\n"
                + "          \"userInsightLocation\": {\n"
                + "            \"city\": \"MALAPURAM\",\n"
                + "            \"state\": \"KERALA\"\n"
                + "          }\n"
                + "        },\n"
                + "        \"IP\": \"49.15.203.205\"\n"
                + "      },\n"
                + "      \"sdkAdId\": \"\",\n"
                + "      \"pincode\": \"679339\",\n"
                + "      \"sessionId\": \"SI49EA9419F8264F708B787ED78327D9AF\",\n"
                + "      \"adId\": \"\",\n"
                + "      \"visitId\": \"0e8d5c7c3cbd37b525370c5d37118eb2-1518282840820\",\n"
                + "      \"userAgent\": {\n"
                + "        \"osInfo\": {\n"
                + "          \"version\": \"5.1\",\n"
                + "          \"family\": \"Android\"\n"
                + "        },\n"
                + "        \"appInfo\": {\n"
                + "          \"version\": \"860400\",\n"
                + "          \"type\": \"Retail\"\n"
                + "        },\n"
                + "        \"deviceInfo\": {\n"
                + "          \"type\": \"Mobile\",\n"
                + "          \"deviceId\": \"0e8d5c7c3cbd37b525370c5d37118eb2\",\n"
                + "          \"family\": \"Micromax E451\"\n"
                + "        },\n"
                + "        \"browserInfo\": {\n"
                + "          \"version\": \"59.0.3071\",\n"
                + "          \"family\": \"Chrome Mobile\"\n"
                + "        }\n"
                + "      },\n"
                + "      \"abIds\": [\n"
                + "        \"97884dfe\",\n"
                + "        \"c8381068\"\n"
                + "      ],\n"
                + "      \"isPreprod\": false,\n"
                + "      \"networkType\": \"4G\",\n"
                + "      \"accountId\": \"ACCC30833EB03F94598B33FE249CB471B55G\"\n"
                + "    }\n"
                + "  },\n"
                + "  \"children\": {\n"
                + "    \"fkint/cp/ca_discover/ProductPageServed\": [\n"
                + "      {\n"
                + "        \"eventId\": \"e1781649-6572-4e94-8c45-9b76adfe567b.BELEEVDNNWHPCFG5\",\n"
                + "        \"eventTime\": 1518283236000,\n"
                + "        \"traceId\": \"a06dfe00-44b6-4cba-984c-6ab4551f05f3\",\n"
                + "        \"seqId\": \"001518283236000000000\",\n"
                + "        \"ingestedAt\": 1518283236743,\n"
                + "        \"parentId\": \"e1781649-6572-4e94-8c45-9b76adfe567b\",\n"
                + "        \"test\": null,\n"
                + "        \"parentVersion\": null,\n"
                + "        \"schemaVersion\": \"1.10\",\n"
                + "        \"encodingType\": \"JSON\",\n"
                + "        \"data\": {\n"
                + "          \"itemId\": \"ITMEEVDNWESTGWZ8\",\n"
                + "          \"analyticsInfo\": {\n"
                + "            \"superCategory\": \"MenAccessory\",\n"
                + "            \"category\": \"MenFashionAccessory\",\n"
                + "            \"subCategory\": \"FashionBeltBuckle\",\n"
                + "            \"vertical\": \"FashionBelt\"\n"
                + "          },\n"
                + "          \"fetchId\": \"e1781649-6572-4e94-8c45-9b76adfe567b.BELEEVDNNWHPCFG5\",\n"
                + "          \"swatches\": [\n"
                + "            {\n"
                + "              \"attribute\": \"color\",\n"
                + "              \"option\": \"Black\"\n"
                + "            }\n"
                + "          ],\n"
                + "          \"vertical\": \"belt\",\n"
                + "          \"isEbook\": false,\n"
                + "          \"isVideoAvaiable\": false,\n"
                + "          \"isImagesAvailable\": false,\n"
                + "          \"listings\": [\n"
                + "            {\n"
                + "              \"offerIds\": [\n"
                + "                \"nb:mp:015c17ce07\",\n"
                + "                \"nb:mp:0105674208\",\n"
                + "                \"nb:mp:0081b76202\",\n"
                + "                \"nb:mp:00f67dbb31\",\n"
                + "                \"nb:mp:01d7a6be08\",\n"
                + "                \"nb:mp:01f4e4dd06\"\n"
                + "              ],\n"
                + "              \"deliveryOptionInfo\": [\n"
                + "                {\n"
                + "                  \"ffApplied\": false,\n"
                + "                  \"codAvailable\": true,\n"
                + "                  \"price\": {\n"
                + "                    \"currency\": \"INR\",\n"
                + "                    \"value\": 65\n"
                + "                  },\n"
                + "                  \"serviceable\": true,\n"
                + "                  \"deliveryDate\": 1519064999000,\n"
                + "                  \"speed\": \"REGULAR\"\n"
                + "                }\n"
                + "              ],\n"
                + "              \"availibilityStatus\": \"In Stock\",\n"
                + "              \"listingId\": \"LSTBELEEVDNNWHPCFG5XTR99D\",\n"
                + "              \"listingState\": \"current\",\n"
                + "              \"mrp\": 599,\n"
                + "              \"offerCount\": 6,\n"
                + "              \"finalPrice\": 177,\n"
                + "              \"fsp\": 112,\n"
                + "              \"isServiceable\": true,\n"
                + "              \"offerSummary\": [\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:015c17ce07\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_PHONEPE_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:0105674208\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:0081b76202\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:00f67dbb31\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"LISTING_NON_FK_FULFILLED_OFFER\",\n"
                + "                  \"id\": \"nb:mp:01d7a6be08\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"LISTING_NON_FK_FULFILLED_OFFER\",\n"
                + "                  \"id\": \"nb:mp:01f4e4dd06\"\n"
                + "                }\n"
                + "              ],\n"
                + "              \"sellerId\": \"608f062b459e4027\",\n"
                + "              \"flipkartAdvantage\": false\n"
                + "            },\n"
                + "            {\n"
                + "              \"offerIds\": [\n"
                + "                \"nb:mp:015c17ce07\",\n"
                + "                \"nb:mp:0105674208\",\n"
                + "                \"nb:mp:0081b76202\",\n"
                + "                \"nb:mp:00f67dbb31\",\n"
                + "                \"nb:mp:01d7a6be08\",\n"
                + "                \"nb:mp:01f4e4dd06\"\n"
                + "              ],\n"
                + "              \"deliveryOptionInfo\": [\n"
                + "                {\n"
                + "                  \"ffApplied\": false,\n"
                + "                  \"codAvailable\": true,\n"
                + "                  \"price\": {\n"
                + "                    \"currency\": \"INR\",\n"
                + "                    \"value\": 58\n"
                + "                  },\n"
                + "                  \"serviceable\": true,\n"
                + "                  \"deliveryDate\": 1519151399000,\n"
                + "                  \"speed\": \"REGULAR\"\n"
                + "                }\n"
                + "              ],\n"
                + "              \"availibilityStatus\": \"In Stock\",\n"
                + "              \"listingId\": \"LSTBELEEVDNNWHPCFG5SOSPHT\",\n"
                + "              \"listingState\": \"current\",\n"
                + "              \"mrp\": 599,\n"
                + "              \"offerCount\": 6,\n"
                + "              \"finalPrice\": 198,\n"
                + "              \"fsp\": 140,\n"
                + "              \"isServiceable\": true,\n"
                + "              \"offerSummary\": [\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:015c17ce07\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_PHONEPE_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:0105674208\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:0081b76202\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:00f67dbb31\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"LISTING_NON_FK_FULFILLED_OFFER\",\n"
                + "                  \"id\": \"nb:mp:01d7a6be08\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"LISTING_NON_FK_FULFILLED_OFFER\",\n"
                + "                  \"id\": \"nb:mp:01f4e4dd06\"\n"
                + "                }\n"
                + "              ],\n"
                + "              \"sellerId\": \"14caca4d3acf4b76\",\n"
                + "              \"flipkartAdvantage\": false\n"
                + "            },\n"
                + "            {\n"
                + "              \"offerIds\": [\n"
                + "                \"nb:mp:015c17ce07\",\n"
                + "                \"nb:mp:0105674208\",\n"
                + "                \"nb:mp:0081b76202\",\n"
                + "                \"nb:mp:00f67dbb31\",\n"
                + "                \"nb:mp:01d7a6be08\",\n"
                + "                \"nb:mp:01f4e4dd06\"\n"
                + "              ],\n"
                + "              \"deliveryOptionInfo\": [\n"
                + "                {\n"
                + "                  \"ffApplied\": false,\n"
                + "                  \"codAvailable\": true,\n"
                + "                  \"price\": {\n"
                + "                    \"currency\": \"INR\",\n"
                + "                    \"value\": 58\n"
                + "                  },\n"
                + "                  \"serviceable\": true,\n"
                + "                  \"deliveryDate\": 1519064999000,\n"
                + "                  \"speed\": \"REGULAR\"\n"
                + "                }\n"
                + "              ],\n"
                + "              \"availibilityStatus\": \"In Stock\",\n"
                + "              \"listingId\": \"LSTBELEEVDNNWHPCFG5NHDRPJ\",\n"
                + "              \"listingState\": \"current\",\n"
                + "              \"mrp\": 599,\n"
                + "              \"offerCount\": 6,\n"
                + "              \"finalPrice\": 207,\n"
                + "              \"fsp\": 149,\n"
                + "              \"isServiceable\": true,\n"
                + "              \"offerSummary\": [\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:015c17ce07\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_PHONEPE_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:0105674208\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:0081b76202\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:00f67dbb31\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"LISTING_NON_FK_FULFILLED_OFFER\",\n"
                + "                  \"id\": \"nb:mp:01d7a6be08\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"LISTING_NON_FK_FULFILLED_OFFER\",\n"
                + "                  \"id\": \"nb:mp:01f4e4dd06\"\n"
                + "                }\n"
                + "              ],\n"
                + "              \"sellerId\": \"a98dbbb8c75e4fe9\",\n"
                + "              \"flipkartAdvantage\": false\n"
                + "            },\n"
                + "            {\n"
                + "              \"offerIds\": [\n"
                + "                \"nb:mp:015c17ce07\",\n"
                + "                \"nb:mp:0105674208\",\n"
                + "                \"nb:mp:0081b76202\",\n"
                + "                \"nb:mp:00f67dbb31\",\n"
                + "                \"nb:mp:01d7a6be08\",\n"
                + "                \"nb:mp:01f4e4dd06\"\n"
                + "              ],\n"
                + "              \"deliveryOptionInfo\": [\n"
                + "                {\n"
                + "                  \"ffApplied\": false,\n"
                + "                  \"codAvailable\": true,\n"
                + "                  \"price\": {\n"
                + "                    \"currency\": \"INR\",\n"
                + "                    \"value\": 58\n"
                + "                  },\n"
                + "                  \"serviceable\": true,\n"
                + "                  \"deliveryDate\": 1519064999000,\n"
                + "                  \"speed\": \"REGULAR\"\n"
                + "                }\n"
                + "              ],\n"
                + "              \"availibilityStatus\": \"In Stock\",\n"
                + "              \"listingId\": \"LSTBELEEVDNNWHPCFG5DU2RER\",\n"
                + "              \"listingState\": \"current\",\n"
                + "              \"mrp\": 599,\n"
                + "              \"offerCount\": 6,\n"
                + "              \"finalPrice\": 278,\n"
                + "              \"fsp\": 220,\n"
                + "              \"isServiceable\": true,\n"
                + "              \"offerSummary\": [\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:015c17ce07\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_PHONEPE_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:0105674208\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:0081b76202\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:00f67dbb31\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"LISTING_NON_FK_FULFILLED_OFFER\",\n"
                + "                  \"id\": \"nb:mp:01d7a6be08\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"LISTING_NON_FK_FULFILLED_OFFER\",\n"
                + "                  \"id\": \"nb:mp:01f4e4dd06\"\n"
                + "                }\n"
                + "              ],\n"
                + "              \"sellerId\": \"10de58d43a4648ea\",\n"
                + "              \"flipkartAdvantage\": false\n"
                + "            }\n"
                + "          ],\n"
                + "          \"productState\": \"IN_STOCK\",\n"
                + "          \"listingsCount\": 4,\n"
                + "          \"isVisualDiscoverEnabled\": false,\n"
                + "          \"productFamily\": [],\n"
                + "          \"isDigital\": false,\n"
                + "          \"isSwatchAvailable\": false,\n"
                + "          \"ugc\": {\n"
                + "            \"reviewCount\": 6,\n"
                + "            \"ratingBase\": 5,\n"
                + "            \"avgRating\": 3.0,\n"
                + "            \"ratingCount\": 35\n"
                + "          },\n"
                + "          \"marketplaceId\": \"FLIPKART\",\n"
                + "          \"importanceType\": \"NONCORE\",\n"
                + "          \"urgency\": {\n"
                + "            \"messageShown\": false\n"
                + "          },\n"
                + "          \"productId\": \"BELEEVDNNWHPCFG5\"\n"
                + "        }\n"
                + "      }\n"
                + "    ]\n"
                + "  }\n"
                + "}\n";

        String jsonDef = "{\n"
                + "  \"additionalProperties\" : false,\n"
                + "  \"type\" : \"object\",\n"
                + "  \"properties\" : {\n"
                + "    \"core\" : {\n"
                + "      \"additionalProperties\" : false,\n"
                + "      \"type\" : \"object\",\n"
                + "      \"properties\" : {\n"
                + "        \"sourceClient\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"string\",\n"
                + "            \"enum\" : [ \"Mapi\", \"Msite\", \"Website\", \"mWebsite\", \"AndroidApp\", \"IOSApp\", \"EbookApp\", \"WindowsApp\", \"AndroidEbookApp\", \"WindowsEbookApp\", \"IOSEbookApp\" ]\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"requestId\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"string\"\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"referrerRequestId\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"string\"\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"URI\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"string\"\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"timestamp\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"maximum\" : 9223372036854775807,\n"
                + "            \"type\" : \"integer\",\n"
                + "            \"minimum\" : -9223372036854775808\n"
                + "          } ]\n"
                + "        }\n"
                + "      },\n"
                + "      \"required\" : [ ]\n"
                + "    },\n"
                + "    \"debug\" : {\n"
                + "      \"additionalProperties\" : false,\n"
                + "      \"type\" : \"object\",\n"
                + "      \"properties\" : {\n"
                + "        \"hostName\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"string\"\n"
                + "          } ]\n"
                + "        }\n"
                + "      },\n"
                + "      \"required\" : [ ]\n"
                + "    },\n"
                + "    \"visit\" : {\n"
                + "      \"additionalProperties\" : false,\n"
                + "      \"type\" : \"object\",\n"
                + "      \"properties\" : {\n"
                + "        \"pincode\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"string\"\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"cartId\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"string\"\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"isPreprod\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"boolean\"\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"trafficType\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"string\"\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"userAgent\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"additionalProperties\" : false,\n"
                + "            \"type\" : \"object\",\n"
                + "            \"properties\" : {\n"
                + "              \"osInfo\" : {\n"
                + "                \"anyOf\" : [ {\n"
                + "                  \"type\" : \"null\"\n"
                + "                }, {\n"
                + "                  \"additionalProperties\" : false,\n"
                + "                  \"type\" : \"object\",\n"
                + "                  \"properties\" : {\n"
                + "                    \"family\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"type\" : \"string\"\n"
                + "                      } ]\n"
                + "                    },\n"
                + "                    \"version\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"type\" : \"string\"\n"
                + "                      } ]\n"
                + "                    },\n"
                + "                    \"versionPopularName\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"type\" : \"string\"\n"
                + "                      } ]\n"
                + "                    }\n"
                + "                  },\n"
                + "                  \"required\" : [ ]\n"
                + "                } ]\n"
                + "              },\n"
                + "              \"appInfo\" : {\n"
                + "                \"anyOf\" : [ {\n"
                + "                  \"type\" : \"null\"\n"
                + "                }, {\n"
                + "                  \"additionalProperties\" : false,\n"
                + "                  \"type\" : \"object\",\n"
                + "                  \"properties\" : {\n"
                + "                    \"type\" : {\n"
                + "                      \"type\" : \"string\"\n"
                + "                    },\n"
                + "                    \"version\" : {\n"
                + "                      \"type\" : \"string\"\n"
                + "                    }\n"
                + "                  },\n"
                + "                  \"required\" : [ \"type\", \"version\" ]\n"
                + "                } ]\n"
                + "              },\n"
                + "              \"browserInfo\" : {\n"
                + "                \"anyOf\" : [ {\n"
                + "                  \"type\" : \"null\"\n"
                + "                }, {\n"
                + "                  \"additionalProperties\" : false,\n"
                + "                  \"type\" : \"object\",\n"
                + "                  \"properties\" : {\n"
                + "                    \"family\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"type\" : \"string\"\n"
                + "                      } ]\n"
                + "                    },\n"
                + "                    \"version\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"type\" : \"string\"\n"
                + "                      } ]\n"
                + "                    }\n"
                + "                  },\n"
                + "                  \"required\" : [ ]\n"
                + "                } ]\n"
                + "              },\n"
                + "              \"deviceInfo\" : {\n"
                + "                \"anyOf\" : [ {\n"
                + "                  \"type\" : \"null\"\n"
                + "                }, {\n"
                + "                  \"additionalProperties\" : false,\n"
                + "                  \"type\" : \"object\",\n"
                + "                  \"properties\" : {\n"
                + "                    \"family\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"type\" : \"string\"\n"
                + "                      } ]\n"
                + "                    },\n"
                + "                    \"type\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"type\" : \"string\"\n"
                + "                      } ]\n"
                + "                    },\n"
                + "                    \"deviceId\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"type\" : \"string\"\n"
                + "                      } ]\n"
                + "                    }\n"
                + "                  },\n"
                + "                  \"required\" : [ ]\n"
                + "                } ]\n"
                + "              }\n"
                + "            },\n"
                + "            \"required\" : [ ]\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"sessionId\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"string\"\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"sdkAdId\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"string\"\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"mpId\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"string\"\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"accountId\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"string\"\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"abIds\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"additionalItems\" : false,\n"
                + "            \"type\" : \"array\",\n"
                + "            \"items\" : {\n"
                + "              \"type\" : \"string\"\n"
                + "            }\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"adId\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"string\"\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"abImpressionId\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"string\"\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"visitId\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"string\"\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"location\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"additionalProperties\" : false,\n"
                + "            \"type\" : \"object\",\n"
                + "            \"properties\" : {\n"
                + "              \"country\" : {\n"
                + "                \"anyOf\" : [ {\n"
                + "                  \"type\" : \"null\"\n"
                + "                }, {\n"
                + "                  \"type\" : \"string\"\n"
                + "                } ]\n"
                + "              },\n"
                + "              \"city\" : {\n"
                + "                \"anyOf\" : [ {\n"
                + "                  \"type\" : \"null\"\n"
                + "                }, {\n"
                + "                  \"type\" : \"string\"\n"
                + "                } ]\n"
                + "              },\n"
                + "              \"IP\" : {\n"
                + "                \"type\" : \"string\"\n"
                + "              },\n"
                + "              \"latitude\" : {\n"
                + "                \"anyOf\" : [ {\n"
                + "                  \"type\" : \"null\"\n"
                + "                }, {\n"
                + "                  \"maximum\" : 1.7976931348623157E308,\n"
                + "                  \"type\" : \"number\",\n"
                + "                  \"minimum\" : -1.7976931348623157E308\n"
                + "                } ]\n"
                + "              },\n"
                + "              \"state\" : {\n"
                + "                \"anyOf\" : [ {\n"
                + "                  \"type\" : \"null\"\n"
                + "                }, {\n"
                + "                  \"type\" : \"string\"\n"
                + "                } ]\n"
                + "              },\n"
                + "              \"longitude\" : {\n"
                + "                \"anyOf\" : [ {\n"
                + "                  \"type\" : \"null\"\n"
                + "                }, {\n"
                + "                  \"maximum\" : 1.7976931348623157E308,\n"
                + "                  \"type\" : \"number\",\n"
                + "                  \"minimum\" : -1.7976931348623157E308\n"
                + "                } ]\n"
                + "              },\n"
                + "              \"info\" : {\n"
                + "                \"anyOf\" : [ {\n"
                + "                  \"type\" : \"null\"\n"
                + "                }, {\n"
                + "                  \"additionalProperties\" : false,\n"
                + "                  \"type\" : \"object\",\n"
                + "                  \"properties\" : {\n"
                + "                    \"ipLocation\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"additionalProperties\" : false,\n"
                + "                        \"type\" : \"object\",\n"
                + "                        \"properties\" : {\n"
                + "                          \"country\" : {\n"
                + "                            \"anyOf\" : [ {\n"
                + "                              \"type\" : \"null\"\n"
                + "                            }, {\n"
                + "                              \"type\" : \"string\"\n"
                + "                            } ]\n"
                + "                          },\n"
                + "                          \"city\" : {\n"
                + "                            \"anyOf\" : [ {\n"
                + "                              \"type\" : \"null\"\n"
                + "                            }, {\n"
                + "                              \"type\" : \"string\"\n"
                + "                            } ]\n"
                + "                          },\n"
                + "                          \"ip\" : {\n"
                + "                            \"anyOf\" : [ {\n"
                + "                              \"type\" : \"null\"\n"
                + "                            }, {\n"
                + "                              \"type\" : \"string\"\n"
                + "                            } ]\n"
                + "                          },\n"
                + "                          \"state\" : {\n"
                + "                            \"anyOf\" : [ {\n"
                + "                              \"type\" : \"null\"\n"
                + "                            }, {\n"
                + "                              \"type\" : \"string\"\n"
                + "                            } ]\n"
                + "                          }\n"
                + "                        },\n"
                + "                        \"required\" : [ ]\n"
                + "                      } ]\n"
                + "                    },\n"
                + "                    \"userInsightLocation\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"additionalProperties\" : false,\n"
                + "                        \"type\" : \"object\",\n"
                + "                        \"properties\" : {\n"
                + "                          \"country\" : {\n"
                + "                            \"anyOf\" : [ {\n"
                + "                              \"type\" : \"null\"\n"
                + "                            }, {\n"
                + "                              \"type\" : \"string\"\n"
                + "                            } ]\n"
                + "                          },\n"
                + "                          \"city\" : {\n"
                + "                            \"anyOf\" : [ {\n"
                + "                              \"type\" : \"null\"\n"
                + "                            }, {\n"
                + "                              \"type\" : \"string\"\n"
                + "                            } ]\n"
                + "                          },\n"
                + "                          \"state\" : {\n"
                + "                            \"anyOf\" : [ {\n"
                + "                              \"type\" : \"null\"\n"
                + "                            }, {\n"
                + "                              \"type\" : \"string\"\n"
                + "                            } ]\n"
                + "                          }\n"
                + "                        },\n"
                + "                        \"required\" : [ ]\n"
                + "                      } ]\n"
                + "                    },\n"
                + "                    \"geolocation\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"additionalProperties\" : false,\n"
                + "                        \"type\" : \"object\",\n"
                + "                        \"properties\" : {\n"
                + "                          \"country\" : {\n"
                + "                            \"anyOf\" : [ {\n"
                + "                              \"type\" : \"null\"\n"
                + "                            }, {\n"
                + "                              \"type\" : \"string\"\n"
                + "                            } ]\n"
                + "                          },\n"
                + "                          \"isLatest\" : {\n"
                + "                            \"anyOf\" : [ {\n"
                + "                              \"type\" : \"null\"\n"
                + "                            }, {\n"
                + "                              \"type\" : \"boolean\"\n"
                + "                            } ]\n"
                + "                          },\n"
                + "                          \"city\" : {\n"
                + "                            \"anyOf\" : [ {\n"
                + "                              \"type\" : \"null\"\n"
                + "                            }, {\n"
                + "                              \"type\" : \"string\"\n"
                + "                            } ]\n"
                + "                          },\n"
                + "                          \"state\" : {\n"
                + "                            \"anyOf\" : [ {\n"
                + "                              \"type\" : \"null\"\n"
                + "                            }, {\n"
                + "                              \"type\" : \"string\"\n"
                + "                            } ]\n"
                + "                          },\n"
                + "                          \"timestamp\" : {\n"
                + "                            \"anyOf\" : [ {\n"
                + "                              \"type\" : \"null\"\n"
                + "                            }, {\n"
                + "                              \"maximum\" : 9223372036854775807,\n"
                + "                              \"type\" : \"integer\",\n"
                + "                              \"minimum\" : -9223372036854775808\n"
                + "                            } ]\n"
                + "                          }\n"
                + "                        },\n"
                + "                        \"required\" : [ ]\n"
                + "                      } ]\n"
                + "                    }\n"
                + "                  },\n"
                + "                  \"required\" : [ ]\n"
                + "                } ]\n"
                + "              }\n"
                + "            },\n"
                + "            \"required\" : [ \"IP\" ]\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"isCrawler\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"boolean\"\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"networkType\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"string\"\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"lockinUserState\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"additionalProperties\" : false,\n"
                + "            \"type\" : \"object\",\n"
                + "            \"properties\" : {\n"
                + "              \"membershipStatus\" : {\n"
                + "                \"type\" : \"string\"\n"
                + "              }\n"
                + "            },\n"
                + "            \"required\" : [ \"membershipStatus\" ]\n"
                + "          } ]\n"
                + "        },\n"
                + "        \"visitorId\" : {\n"
                + "          \"anyOf\" : [ {\n"
                + "            \"type\" : \"null\"\n"
                + "          }, {\n"
                + "            \"type\" : \"string\"\n"
                + "          } ]\n"
                + "        }\n"
                + "      },\n"
                + "      \"required\" : [ ]\n"
                + "    }\n"
                + "  },\n"
                + "  \"required\" : [ \"core\", \"debug\", \"visit\" ]\n"
                + "}";

        jsonInString = "{\"eventId\":\"e1781649-6572-4e94-8c45-9b76adfe567b\",\"eventTime\":1518283236000,\"traceId\":\"a06dfe00-44b6-4cba-984c-6ab4551f05f3\",\"seqId\":\"001518283236000000000\",\"ingestedAt\":1518283236743,\"parentId\":null,\"test\":null,\"parentVersion\":null,\"schemaVersion\":\"2.5\",\"encodingType\":\"JSON\",\"data\":{\"debug\":{\"hostName\":\"fk-mobile-api-mapi-client-grp-18-457494\"},\"core\":{\"timestamp\":1518283236742,\"requestId\":\"e1781649-6572-4e94-8c45-9b76adfe567b\",\"sourceClient\":\"AndroidApp\",\"URI\":\"/3/page/dynamic/product\"},\"visit\":{\"visitorId\":\"VI1816BC5E890745DC8C0531FBC956F878\",\"location\":{\"info\":{\"geolocation\":{},\"ipLocation\":{\"ip\":\"49.15.203.205\",\"country\":\"India\",\"state\":\"Kerala\",\"city\":\"UNKNOWN\"},\"userInsightLocation\":{\"city\":\"MALAPURAM\",\"state\":\"KERALA\"}},\"IP\":\"49.15.203.205\"},\"sdkAdId\":\"\",\"pincode\":\"679339\",\"sessionId\":\"SI49EA9419F8264F708B787ED78327D9AF\",\"adId\":\"\",\"visitId\":\"0e8d5c7c3cbd37b525370c5d37118eb2-1518282840820\",\"userAgent\":{\"osInfo\":{\"version\":\"5.1\",\"family\":\"Android\"},\"appInfo\":{\"version\":\"860400\",\"type\":\"Retail\"},\"deviceInfo\":{\"type\":\"Mobile\",\"deviceId\":\"0e8d5c7c3cbd37b525370c5d37118eb2\",\"family\":\"Micromax E451\"},\"browserInfo\":{\"version\":\"59.0.3071\",\"family\":\"Chrome Mobile\"}},\"abIds\":[\"97884dfe\",\"c8381068\"],\"isPreprod\":false,\"networkType\":\"4G\",\"accountId\":\"ACCC30833EB03F94598B33FE249CB471B55G\"}}}";

        String jsonInString2 = "{\n"
                + "        \"eventId\": \"e1781649-6572-4e94-8c45-9b76adfe567b.BELEEVDNNWHPCFG5\",\n"
                + "        \"eventTime\": 1518283236000,\n"
                + "        \"traceId\": \"a06dfe00-44b6-4cba-984c-6ab4551f05f3\",\n"
                + "        \"seqId\": \"001518283236000000000\",\n"
                + "        \"ingestedAt\": 1518283236743,\n"
                + "        \"parentId\": \"e1781649-6572-4e94-8c45-9b76adfe567b\",\n"
                + "        \"test\": null,\n"
                + "        \"parentVersion\": null,\n"
                + "        \"schemaVersion\": \"1.10\",\n"
                + "        \"encodingType\": \"JSON\",\n"
                + "        \"data\": {\n"
                + "          \"itemId\": \"ITMEEVDNWESTGWZ8\",\n"
                + "          \"analyticsInfo\": {\n"
                + "            \"superCategory\": \"MenAccessory\",\n"
                + "            \"category\": \"MenFashionAccessory\",\n"
                + "            \"subCategory\": \"FashionBeltBuckle\",\n"
                + "            \"vertical\": \"FashionBelt\"\n"
                + "          },\n"
                + "          \"fetchId\": \"e1781649-6572-4e94-8c45-9b76adfe567b.BELEEVDNNWHPCFG5\",\n"
                + "          \"swatches\": [\n"
                + "            {\n"
                + "              \"attribute\": \"color\",\n"
                + "              \"option\": \"Black\"\n"
                + "            }\n"
                + "          ],\n"
                + "          \"vertical\": \"belt\",\n"
                + "          \"isEbook\": false,\n"
                + "          \"isVideoAvaiable\": false,\n"
                + "          \"isImagesAvailable\": false,\n"
                + "          \"listings\": [\n"
                + "            {\n"
                + "              \"offerIds\": [\n"
                + "                \"nb:mp:015c17ce07\",\n"
                + "                \"nb:mp:0105674208\",\n"
                + "                \"nb:mp:0081b76202\",\n"
                + "                \"nb:mp:00f67dbb31\",\n"
                + "                \"nb:mp:01d7a6be08\",\n"
                + "                \"nb:mp:01f4e4dd06\"\n"
                + "              ],\n"
                + "              \"deliveryOptionInfo\": [\n"
                + "                {\n"
                + "                  \"ffApplied\": false,\n"
                + "                  \"codAvailable\": true,\n"
                + "                  \"price\": {\n"
                + "                    \"currency\": \"INR\",\n"
                + "                    \"value\": 65\n"
                + "                  },\n"
                + "                  \"serviceable\": true,\n"
                + "                  \"deliveryDate\": 1519064999000,\n"
                + "                  \"speed\": \"REGULAR\"\n"
                + "                }\n"
                + "              ],\n"
                + "              \"availibilityStatus\": \"In Stock\",\n"
                + "              \"listingId\": \"LSTBELEEVDNNWHPCFG5XTR99D\",\n"
                + "              \"listingState\": \"current\",\n"
                + "              \"mrp\": 599,\n"
                + "              \"offerCount\": 6,\n"
                + "              \"finalPrice\": 177,\n"
                + "              \"fsp\": 112,\n"
                + "              \"isServiceable\": true,\n"
                + "              \"offerSummary\": [\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:015c17ce07\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_PHONEPE_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:0105674208\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:0081b76202\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:00f67dbb31\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"LISTING_NON_FK_FULFILLED_OFFER\",\n"
                + "                  \"id\": \"nb:mp:01d7a6be08\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"LISTING_NON_FK_FULFILLED_OFFER\",\n"
                + "                  \"id\": \"nb:mp:01f4e4dd06\"\n"
                + "                }\n"
                + "              ],\n"
                + "              \"sellerId\": \"608f062b459e4027\",\n"
                + "              \"flipkartAdvantage\": false\n"
                + "            },\n"
                + "            {\n"
                + "              \"offerIds\": [\n"
                + "                \"nb:mp:015c17ce07\",\n"
                + "                \"nb:mp:0105674208\",\n"
                + "                \"nb:mp:0081b76202\",\n"
                + "                \"nb:mp:00f67dbb31\",\n"
                + "                \"nb:mp:01d7a6be08\",\n"
                + "                \"nb:mp:01f4e4dd06\"\n"
                + "              ],\n"
                + "              \"deliveryOptionInfo\": [\n"
                + "                {\n"
                + "                  \"ffApplied\": false,\n"
                + "                  \"codAvailable\": true,\n"
                + "                  \"price\": {\n"
                + "                    \"currency\": \"INR\",\n"
                + "                    \"value\": 58\n"
                + "                  },\n"
                + "                  \"serviceable\": true,\n"
                + "                  \"deliveryDate\": 1519151399000,\n"
                + "                  \"speed\": \"REGULAR\"\n"
                + "                }\n"
                + "              ],\n"
                + "              \"availibilityStatus\": \"In Stock\",\n"
                + "              \"listingId\": \"LSTBELEEVDNNWHPCFG5SOSPHT\",\n"
                + "              \"listingState\": \"current\",\n"
                + "              \"mrp\": 599,\n"
                + "              \"offerCount\": 6,\n"
                + "              \"finalPrice\": 198,\n"
                + "              \"fsp\": 140,\n"
                + "              \"isServiceable\": true,\n"
                + "              \"offerSummary\": [\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:015c17ce07\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_PHONEPE_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:0105674208\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:0081b76202\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:00f67dbb31\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"LISTING_NON_FK_FULFILLED_OFFER\",\n"
                + "                  \"id\": \"nb:mp:01d7a6be08\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"LISTING_NON_FK_FULFILLED_OFFER\",\n"
                + "                  \"id\": \"nb:mp:01f4e4dd06\"\n"
                + "                }\n"
                + "              ],\n"
                + "              \"sellerId\": \"14caca4d3acf4b76\",\n"
                + "              \"flipkartAdvantage\": false\n"
                + "            },\n"
                + "            {\n"
                + "              \"offerIds\": [\n"
                + "                \"nb:mp:015c17ce07\",\n"
                + "                \"nb:mp:0105674208\",\n"
                + "                \"nb:mp:0081b76202\",\n"
                + "                \"nb:mp:00f67dbb31\",\n"
                + "                \"nb:mp:01d7a6be08\",\n"
                + "                \"nb:mp:01f4e4dd06\"\n"
                + "              ],\n"
                + "              \"deliveryOptionInfo\": [\n"
                + "                {\n"
                + "                  \"ffApplied\": false,\n"
                + "                  \"codAvailable\": true,\n"
                + "                  \"price\": {\n"
                + "                    \"currency\": \"INR\",\n"
                + "                    \"value\": 58\n"
                + "                  },\n"
                + "                  \"serviceable\": true,\n"
                + "                  \"deliveryDate\": 1519064999000,\n"
                + "                  \"speed\": \"REGULAR\"\n"
                + "                }\n"
                + "              ],\n"
                + "              \"availibilityStatus\": \"In Stock\",\n"
                + "              \"listingId\": \"LSTBELEEVDNNWHPCFG5NHDRPJ\",\n"
                + "              \"listingState\": \"current\",\n"
                + "              \"mrp\": 599,\n"
                + "              \"offerCount\": 6,\n"
                + "              \"finalPrice\": 207,\n"
                + "              \"fsp\": 149,\n"
                + "              \"isServiceable\": true,\n"
                + "              \"offerSummary\": [\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:015c17ce07\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_PHONEPE_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:0105674208\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:0081b76202\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:00f67dbb31\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"LISTING_NON_FK_FULFILLED_OFFER\",\n"
                + "                  \"id\": \"nb:mp:01d7a6be08\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"LISTING_NON_FK_FULFILLED_OFFER\",\n"
                + "                  \"id\": \"nb:mp:01f4e4dd06\"\n"
                + "                }\n"
                + "              ],\n"
                + "              \"sellerId\": \"a98dbbb8c75e4fe9\",\n"
                + "              \"flipkartAdvantage\": false\n"
                + "            },\n"
                + "            {\n"
                + "              \"offerIds\": [\n"
                + "                \"nb:mp:015c17ce07\",\n"
                + "                \"nb:mp:0105674208\",\n"
                + "                \"nb:mp:0081b76202\",\n"
                + "                \"nb:mp:00f67dbb31\",\n"
                + "                \"nb:mp:01d7a6be08\",\n"
                + "                \"nb:mp:01f4e4dd06\"\n"
                + "              ],\n"
                + "              \"deliveryOptionInfo\": [\n"
                + "                {\n"
                + "                  \"ffApplied\": false,\n"
                + "                  \"codAvailable\": true,\n"
                + "                  \"price\": {\n"
                + "                    \"currency\": \"INR\",\n"
                + "                    \"value\": 58\n"
                + "                  },\n"
                + "                  \"serviceable\": true,\n"
                + "                  \"deliveryDate\": 1519064999000,\n"
                + "                  \"speed\": \"REGULAR\"\n"
                + "                }\n"
                + "              ],\n"
                + "              \"availibilityStatus\": \"In Stock\",\n"
                + "              \"listingId\": \"LSTBELEEVDNNWHPCFG5DU2RER\",\n"
                + "              \"listingState\": \"current\",\n"
                + "              \"mrp\": 599,\n"
                + "              \"offerCount\": 6,\n"
                + "              \"finalPrice\": 278,\n"
                + "              \"fsp\": 220,\n"
                + "              \"isServiceable\": true,\n"
                + "              \"offerSummary\": [\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:015c17ce07\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_PHONEPE_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:0105674208\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:0081b76202\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"BASKETPRICE_PAYMENT_DISCOUNT\",\n"
                + "                  \"id\": \"nb:mp:00f67dbb31\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"LISTING_NON_FK_FULFILLED_OFFER\",\n"
                + "                  \"id\": \"nb:mp:01d7a6be08\"\n"
                + "                },\n"
                + "                {\n"
                + "                  \"type\": \"LISTING_NON_FK_FULFILLED_OFFER\",\n"
                + "                  \"id\": \"nb:mp:01f4e4dd06\"\n"
                + "                }\n"
                + "              ],\n"
                + "              \"sellerId\": \"10de58d43a4648ea\",\n"
                + "              \"flipkartAdvantage\": false\n"
                + "            }\n"
                + "          ],\n"
                + "          \"productState\": \"IN_STOCK\",\n"
                + "          \"listingsCount\": 4,\n"
                + "          \"isVisualDiscoverEnabled\": false,\n"
                + "          \"productFamily\": [],\n"
                + "          \"isDigital\": false,\n"
                + "          \"isSwatchAvailable\": false,\n"
                + "          \"ugc\": {\n"
                + "            \"reviewCount\": 6,\n"
                + "            \"ratingBase\": 5,\n"
                + "            \"avgRating\": 3,\n"
                + "            \"ratingCount\": 35\n"
                + "          },\n"
                + "          \"marketplaceId\": \"FLIPKART\",\n"
                + "          \"importanceType\": \"NONCORE\",\n"
                + "          \"urgency\": {\n"
                + "            \"messageShown\": false\n"
                + "          },\n"
                + "          \"productId\": \"BELEEVDNNWHPCFG5\"\n"
                + "        }\n"
                + "      }";

        String jsonDef2 = "{\n"
                + "  \"additionalProperties\" : false,\n"
                + "  \"type\" : \"object\",\n"
                + "  \"properties\" : {\n"
                + "    \"analyticsInfo\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"additionalProperties\" : false,\n"
                + "        \"type\" : \"object\",\n"
                + "        \"properties\" : {\n"
                + "          \"subCategory\" : {\n"
                + "            \"anyOf\" : [ {\n"
                + "              \"type\" : \"null\"\n"
                + "            }, {\n"
                + "              \"type\" : \"string\"\n"
                + "            } ]\n"
                + "          },\n"
                + "          \"superCategory\" : {\n"
                + "            \"anyOf\" : [ {\n"
                + "              \"type\" : \"null\"\n"
                + "            }, {\n"
                + "              \"type\" : \"string\"\n"
                + "            } ]\n"
                + "          },\n"
                + "          \"vertical\" : {\n"
                + "            \"anyOf\" : [ {\n"
                + "              \"type\" : \"null\"\n"
                + "            }, {\n"
                + "              \"type\" : \"string\"\n"
                + "            } ]\n"
                + "          },\n"
                + "          \"category\" : {\n"
                + "            \"anyOf\" : [ {\n"
                + "              \"type\" : \"null\"\n"
                + "            }, {\n"
                + "              \"type\" : \"string\"\n"
                + "            } ]\n"
                + "          }\n"
                + "        },\n"
                + "        \"required\" : [ ]\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"productFamily\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"additionalItems\" : false,\n"
                + "        \"type\" : \"array\",\n"
                + "        \"items\" : {\n"
                + "          \"type\" : \"string\"\n"
                + "        }\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"isEbook\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"type\" : \"boolean\"\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"productId\" : {\n"
                + "      \"type\" : \"string\"\n"
                + "    },\n"
                + "    \"isDigital\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"type\" : \"boolean\"\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"isVisualDiscoverEnabled\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"type\" : \"boolean\"\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"vertical\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"type\" : \"string\"\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"isVideoAvaiable\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"type\" : \"boolean\"\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"productState\" : {\n"
                + "      \"type\" : \"string\"\n"
                + "    },\n"
                + "    \"isSwatchAvailable\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"type\" : \"boolean\"\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"importanceType\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"type\" : \"string\"\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"swatches\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"additionalItems\" : false,\n"
                + "        \"type\" : \"array\",\n"
                + "        \"items\" : {\n"
                + "          \"additionalProperties\" : false,\n"
                + "          \"type\" : \"object\",\n"
                + "          \"properties\" : {\n"
                + "            \"attribute\" : {\n"
                + "              \"type\" : \"string\"\n"
                + "            },\n"
                + "            \"option\" : {\n"
                + "              \"type\" : \"string\"\n"
                + "            }\n"
                + "          },\n"
                + "          \"required\" : [ \"attribute\", \"option\" ]\n"
                + "        }\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"ugc\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"additionalProperties\" : false,\n"
                + "        \"type\" : \"object\",\n"
                + "        \"properties\" : {\n"
                + "          \"reviewCount\" : {\n"
                + "            \"maximum\" : 2147483647,\n"
                + "            \"type\" : \"integer\",\n"
                + "            \"minimum\" : -2147483648\n"
                + "          },\n"
                + "          \"ratingBase\" : {\n"
                + "            \"maximum\" : 2147483647,\n"
                + "            \"type\" : \"integer\",\n"
                + "            \"minimum\" : -2147483648\n"
                + "          },\n"
                + "          \"avgRating\" : {\n"
                + "            \"maximum\" : 1.7976931348623157E308,\n"
                + "            \"type\" : \"number\",\n"
                + "            \"minimum\" : -1.7976931348623157E308\n"
                + "          },\n"
                + "          \"ratingCount\" : {\n"
                + "            \"maximum\" : 2147483647,\n"
                + "            \"type\" : \"integer\",\n"
                + "            \"minimum\" : -2147483648\n"
                + "          }\n"
                + "        },\n"
                + "        \"required\" : [ \"reviewCount\", \"ratingBase\", \"avgRating\", \"ratingCount\" ]\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"marketplaceId\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"type\" : \"string\"\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"itemId\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"type\" : \"string\"\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"listings\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"additionalItems\" : false,\n"
                + "        \"type\" : \"array\",\n"
                + "        \"items\" : {\n"
                + "          \"additionalProperties\" : false,\n"
                + "          \"type\" : \"object\",\n"
                + "          \"properties\" : {\n"
                + "            \"fsp\" : {\n"
                + "              \"anyOf\" : [ {\n"
                + "                \"type\" : \"null\"\n"
                + "              }, {\n"
                + "                \"maximum\" : 2147483647,\n"
                + "                \"type\" : \"integer\",\n"
                + "                \"minimum\" : -2147483648\n"
                + "              } ]\n"
                + "            },\n"
                + "            \"deliveryOptionInfo\" : {\n"
                + "              \"anyOf\" : [ {\n"
                + "                \"type\" : \"null\"\n"
                + "              }, {\n"
                + "                \"additionalItems\" : false,\n"
                + "                \"type\" : \"array\",\n"
                + "                \"items\" : {\n"
                + "                  \"additionalProperties\" : false,\n"
                + "                  \"type\" : \"object\",\n"
                + "                  \"properties\" : {\n"
                + "                    \"codAvailable\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"type\" : \"boolean\"\n"
                + "                      } ]\n"
                + "                    },\n"
                + "                    \"ffApplied\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"type\" : \"boolean\"\n"
                + "                      } ]\n"
                + "                    },\n"
                + "                    \"price\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"additionalProperties\" : false,\n"
                + "                        \"type\" : \"object\",\n"
                + "                        \"properties\" : {\n"
                + "                          \"currency\" : {\n"
                + "                            \"type\" : \"string\"\n"
                + "                          },\n"
                + "                          \"value\" : {\n"
                + "                            \"maximum\" : 2147483647,\n"
                + "                            \"type\" : \"integer\",\n"
                + "                            \"minimum\" : -2147483648\n"
                + "                          }\n"
                + "                        },\n"
                + "                        \"required\" : [ \"currency\", \"value\" ]\n"
                + "                      } ]\n"
                + "                    },\n"
                + "                    \"serviceable\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"type\" : \"boolean\"\n"
                + "                      } ]\n"
                + "                    },\n"
                + "                    \"deliveryDate\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"maximum\" : 9223372036854775807,\n"
                + "                        \"type\" : \"integer\",\n"
                + "                        \"minimum\" : -9223372036854775808\n"
                + "                      } ]\n"
                + "                    },\n"
                + "                    \"speed\" : {\n"
                + "                      \"type\" : \"string\"\n"
                + "                    }\n"
                + "                  },\n"
                + "                  \"required\" : [ \"speed\" ]\n"
                + "                }\n"
                + "              } ]\n"
                + "            },\n"
                + "            \"offerSummary\" : {\n"
                + "              \"anyOf\" : [ {\n"
                + "                \"type\" : \"null\"\n"
                + "              }, {\n"
                + "                \"additionalItems\" : false,\n"
                + "                \"type\" : \"array\",\n"
                + "                \"items\" : {\n"
                + "                  \"additionalProperties\" : false,\n"
                + "                  \"type\" : \"object\",\n"
                + "                  \"properties\" : {\n"
                + "                    \"id\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"type\" : \"string\"\n"
                + "                      } ]\n"
                + "                    },\n"
                + "                    \"type\" : {\n"
                + "                      \"anyOf\" : [ {\n"
                + "                        \"type\" : \"null\"\n"
                + "                      }, {\n"
                + "                        \"type\" : \"string\"\n"
                + "                      } ]\n"
                + "                    }\n"
                + "                  },\n"
                + "                  \"required\" : [ ]\n"
                + "                }\n"
                + "              } ]\n"
                + "            },\n"
                + "            \"offerCount\" : {\n"
                + "              \"anyOf\" : [ {\n"
                + "                \"type\" : \"null\"\n"
                + "              }, {\n"
                + "                \"maximum\" : 2147483647,\n"
                + "                \"type\" : \"integer\",\n"
                + "                \"minimum\" : -2147483648\n"
                + "              } ]\n"
                + "            },\n"
                + "            \"finalPrice\" : {\n"
                + "              \"anyOf\" : [ {\n"
                + "                \"type\" : \"null\"\n"
                + "              }, {\n"
                + "                \"maximum\" : 2147483647,\n"
                + "                \"type\" : \"integer\",\n"
                + "                \"minimum\" : -2147483648\n"
                + "              } ]\n"
                + "            },\n"
                + "            \"mrp\" : {\n"
                + "              \"anyOf\" : [ {\n"
                + "                \"type\" : \"null\"\n"
                + "              }, {\n"
                + "                \"maximum\" : 2147483647,\n"
                + "                \"type\" : \"integer\",\n"
                + "                \"minimum\" : -2147483648\n"
                + "              } ]\n"
                + "            },\n"
                + "            \"listingId\" : {\n"
                + "              \"type\" : \"string\"\n"
                + "            },\n"
                + "            \"offerIds\" : {\n"
                + "              \"anyOf\" : [ {\n"
                + "                \"type\" : \"null\"\n"
                + "              }, {\n"
                + "                \"additionalItems\" : false,\n"
                + "                \"type\" : \"array\",\n"
                + "                \"items\" : {\n"
                + "                  \"type\" : \"string\"\n"
                + "                }\n"
                + "              } ]\n"
                + "            },\n"
                + "            \"isServiceable\" : {\n"
                + "              \"anyOf\" : [ {\n"
                + "                \"type\" : \"null\"\n"
                + "              }, {\n"
                + "                \"type\" : \"boolean\"\n"
                + "              } ]\n"
                + "            },\n"
                + "            \"sellerId\" : {\n"
                + "              \"type\" : \"string\"\n"
                + "            },\n"
                + "            \"flipkartAdvantage\" : {\n"
                + "              \"anyOf\" : [ {\n"
                + "                \"type\" : \"null\"\n"
                + "              }, {\n"
                + "                \"type\" : \"boolean\"\n"
                + "              } ]\n"
                + "            },\n"
                + "            \"exchangeDetails\" : {\n"
                + "              \"anyOf\" : [ {\n"
                + "                \"type\" : \"null\"\n"
                + "              }, {\n"
                + "                \"additionalProperties\" : false,\n"
                + "                \"type\" : \"object\",\n"
                + "                \"properties\" : {\n"
                + "                  \"pincode\" : {\n"
                + "                    \"anyOf\" : [ {\n"
                + "                      \"type\" : \"null\"\n"
                + "                    }, {\n"
                + "                      \"maximum\" : 2147483647,\n"
                + "                      \"type\" : \"integer\",\n"
                + "                      \"minimum\" : -2147483648\n"
                + "                    } ]\n"
                + "                  },\n"
                + "                  \"offerId\" : {\n"
                + "                    \"type\" : \"string\"\n"
                + "                  },\n"
                + "                  \"serviceable\" : {\n"
                + "                    \"anyOf\" : [ {\n"
                + "                      \"type\" : \"null\"\n"
                + "                    }, {\n"
                + "                      \"type\" : \"boolean\"\n"
                + "                    } ]\n"
                + "                  }\n"
                + "                },\n"
                + "                \"required\" : [ \"offerId\" ]\n"
                + "              } ]\n"
                + "            },\n"
                + "            \"availibilityStatus\" : {\n"
                + "              \"anyOf\" : [ {\n"
                + "                \"type\" : \"null\"\n"
                + "              }, {\n"
                + "                \"type\" : \"string\"\n"
                + "              } ]\n"
                + "            },\n"
                + "            \"deliveryDate\" : {\n"
                + "              \"anyOf\" : [ {\n"
                + "                \"type\" : \"null\"\n"
                + "              }, {\n"
                + "                \"type\" : \"string\"\n"
                + "              } ]\n"
                + "            },\n"
                + "            \"listingState\" : {\n"
                + "              \"type\" : \"string\"\n"
                + "            }\n"
                + "          },\n"
                + "          \"required\" : [ \"listingId\", \"sellerId\", \"listingState\" ]\n"
                + "        }\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"fetchId\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"type\" : \"string\"\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"latestVersion\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"type\" : \"string\"\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"urgency\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"additionalProperties\" : false,\n"
                + "        \"type\" : \"object\",\n"
                + "        \"properties\" : {\n"
                + "          \"messageShown\" : {\n"
                + "            \"type\" : \"boolean\"\n"
                + "          },\n"
                + "          \"type\" : {\n"
                + "            \"anyOf\" : [ {\n"
                + "              \"type\" : \"null\"\n"
                + "            }, {\n"
                + "              \"additionalItems\" : false,\n"
                + "              \"type\" : \"array\",\n"
                + "              \"items\" : {\n"
                + "                \"type\" : \"string\"\n"
                + "              }\n"
                + "            } ]\n"
                + "          }\n"
                + "        },\n"
                + "        \"required\" : [ \"messageShown\" ]\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"isImagesAvailable\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"type\" : \"boolean\"\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"exchangeDetails\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"additionalProperties\" : false,\n"
                + "        \"type\" : \"object\",\n"
                + "        \"properties\" : {\n"
                + "          \"pincode\" : {\n"
                + "            \"anyOf\" : [ {\n"
                + "              \"type\" : \"null\"\n"
                + "            }, {\n"
                + "              \"maximum\" : 2147483647,\n"
                + "              \"type\" : \"integer\",\n"
                + "              \"minimum\" : -2147483648\n"
                + "            } ]\n"
                + "          },\n"
                + "          \"offerId\" : {\n"
                + "            \"type\" : \"string\"\n"
                + "          },\n"
                + "          \"serviceable\" : {\n"
                + "            \"anyOf\" : [ {\n"
                + "              \"type\" : \"null\"\n"
                + "            }, {\n"
                + "              \"type\" : \"boolean\"\n"
                + "            } ]\n"
                + "          }\n"
                + "        },\n"
                + "        \"required\" : [ \"offerId\" ]\n"
                + "      } ]\n"
                + "    },\n"
                + "    \"listingsCount\" : {\n"
                + "      \"anyOf\" : [ {\n"
                + "        \"type\" : \"null\"\n"
                + "      }, {\n"
                + "        \"maximum\" : 2147483647,\n"
                + "        \"type\" : \"integer\",\n"
                + "        \"minimum\" : -2147483648\n"
                + "      } ]\n"
                + "    }\n"
                + "  },\n"
                + "  \"required\" : [ \"productId\", \"productState\" ]\n"
                + "}";
        ObjectMapper mapper = new ObjectMapper();
        JsonNode node = mapper.readTree(jsonInString);
        JsonNode node2 = mapper.readTree(jsonInString2);


        JsonSchemaFactory factory = JsonSchemaFactory.builder(JsonSchemaFactory.getInstance()).objectMapper(mapper).build();
        JsonSchema schema = factory.getSchema(jsonDef);
        JsonSchema schema2 = factory.getSchema(jsonDef2);
        LatencyTimer timer = new LatencyTimer("json-test");
        while(true) {

            //schema.validate(node.get("data"));
            schema2.validate(node2.get("data"));
            /*for (int i=0; i<100; i++) {
                Set<ValidationMessage> errors = new LinkedHashSet<ValidationMessage>();
                Collections.unmodifiableSet(errors);
            }*/

            timer.count();
        }
        //System.out.println(validationMessages);


    }
}
